#!/usr/bin/env bash
set -euo pipefail

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

main() {
  require_cmd wg
  require_cmd mkdir

  local out_dir="${1:-generated}"
  mkdir -p "${out_dir}"

  local relay_private relay_public home_private home_public
  relay_private="$(wg genkey)"
  relay_public="$(printf '%s' "${relay_private}" | wg pubkey)"
  home_private="$(wg genkey)"
  home_public="$(printf '%s' "${home_private}" | wg pubkey)"

  cat > "${out_dir}/relay-host.env" <<EOF
# Generated by generate-wireguard-keys.sh
PROXY_SERVICE_NAME=tinyproxy-claude
PROXY_USER=claudeproxy
PROXY_PORT=18443
PROXY_LISTEN=127.0.0.1
PROXY_TIMEOUT=600
PROXY_MAX_CLIENTS=100

WG_INTERFACE=wg-claude
WG_ADDRESS=10.14.0.2/24
WG_PRIVATE_KEY=${relay_private}
WG_PEER_PUBLIC_KEY=${home_public}
WG_ENDPOINT=replace-with-your-home-public-ip-or-ddns:51820
WG_ALLOWED_IPS=0.0.0.0/0
WG_PERSISTENT_KEEPALIVE=25
WG_ROUTE_TABLE_ID=184
EOF

  cat > "${out_dir}/home-gateway.env" <<EOF
# Generated by generate-wireguard-keys.sh
WG_INTERFACE=wg-home
WG_ADDRESS=10.14.0.1/24
WG_LISTEN_PORT=51820
WG_PRIVATE_KEY=${home_private}

WG_CLIENT_PUBLIC_KEY=${relay_public}
WG_CLIENT_ALLOWED_IP=10.14.0.2/32

WAN_INTERFACE=replace-with-your-home-linux-default-interface
EOF

  cat <<EOF
Generated:
  ${out_dir}/relay-host.env
  ${out_dir}/home-gateway.env

Relay public key:
  ${relay_public}

Home public key:
  ${home_public}

Next:
  1. Edit ${out_dir}/home-gateway.env and set WAN_INTERFACE
  2. Edit ${out_dir}/relay-host.env and set WG_ENDPOINT
  3. Run detect-wan-interface.sh on the home Linux host if you do not know WAN_INTERFACE
EOF
}

main "$@"
